-- Positive case
DECLARE
    V_STOCK_ID KOPELDAV.STOCK_TRANSACTION.STOCK_ID%TYPE := 1;
    V_INVESTOR_ID KOPELDAV.STOCK_TRANSACTION.INVESTOR_ID%TYPE := 13;
    V_TYPE KOPELDAV.STOCK_TRANSACTION.TYPE%TYPE := 'BUY';
    V_AMOUNT KOPELDAV.STOCK_TRANSACTION.AMOUNT%TYPE := 1;
BEGIN
    MAKE_STOCK_TRANSACTION.MAKE_TRANSACTION(V_STOCK_ID, V_INVESTOR_ID, V_TYPE, V_AMOUNT);
END;

-- Negative case
DECLARE
    V_STOCK_ID KOPELDAV.STOCK_TRANSACTION.STOCK_ID%TYPE := 1;
    V_INVESTOR_ID KOPELDAV.STOCK_TRANSACTION.INVESTOR_ID%TYPE := 13;
    V_TYPE KOPELDAV.STOCK_TRANSACTION.TYPE%TYPE := 'BUY';
    V_AMOUNT KOPELDAV.STOCK_TRANSACTION.AMOUNT%TYPE := 100000000;
BEGIN
    MAKE_STOCK_TRANSACTION.MAKE_TRANSACTION(V_STOCK_ID, V_INVESTOR_ID, V_TYPE, V_AMOUNT);
END;
