-- Create script

-- Remove conflicting tables
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE address CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE country CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE investor CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE portfolio CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE segment CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE stock CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE verified CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE stock_transaction CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
-- End of removing

CREATE TABLE address (
    address_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    country_id NUMBER NOT NULL,
    city VARCHAR2(30) NOT NULL,
    street VARCHAR2(30) NOT NULL,
    zip VARCHAR2(5) NOT NULL
);
ALTER TABLE address ADD CONSTRAINT pk_address PRIMARY KEY (address_id);

CREATE TABLE country (
    country_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR2(30) NOT NULL
);
ALTER TABLE country ADD CONSTRAINT pk_country PRIMARY KEY (country_id);

CREATE TABLE investor (
    investor_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address_id NUMBER NOT NULL,
    firstname VARCHAR2(30) NOT NULL,
    lastname VARCHAR2(30) NOT NULL,
    available_cash NUMBER NOT NULL,
    id_card VARCHAR2(256) NULL,
    passport VARCHAR2(256) NULL
);
ALTER TABLE investor ADD CONSTRAINT pk_investor PRIMARY KEY (investor_id);
ALTER TABLE investor ADD CONSTRAINT uc_investor_id_card UNIQUE (id_card);
ALTER TABLE investor ADD CONSTRAINT uc_investor_passport UNIQUE (passport);

CREATE TABLE portfolio (
    porfolio_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    investor_id NUMBER NOT NULL,
    amount NUMBER NOT NULL,
    value NUMBER NOT NULL
);
ALTER TABLE portfolio ADD CONSTRAINT pk_portfolio PRIMARY KEY (porfolio_id);

CREATE TABLE segment (
    segment_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR2(256) NOT NULL
);
ALTER TABLE segment ADD CONSTRAINT pk_segment PRIMARY KEY (segment_id);

CREATE TABLE stock (
    stock_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    segment_id NUMBER NOT NULL,
    name VARCHAR2(256) NOT NULL,
    symbol VARCHAR2(10) NOT NULL,
    price NUMBER NOT NULL,
    volume NUMBER NOT NULL
);
ALTER TABLE stock ADD CONSTRAINT pk_stock PRIMARY KEY (stock_id);
ALTER TABLE stock ADD CONSTRAINT uc_stock_symbol UNIQUE (symbol);

CREATE TABLE stock_transaction (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stock_id NUMBER NOT NULL,
    investor_id NUMBER NOT NULL,
    type VARCHAR2(10) NOT NULL,
    amount NUMBER NOT NULL,
    transaction_date DATE NOT NULL
);
ALTER TABLE stock_transaction ADD CONSTRAINT pk_transaction PRIMARY KEY (transaction_id);

CREATE TABLE verified (
    investor_id NUMBER NOT NULL,
    status VARCHAR2(5) NOT NULL
);
ALTER TABLE verified ADD CONSTRAINT pk_verified PRIMARY KEY (investor_id);

ALTER TABLE address ADD CONSTRAINT fk_address_country FOREIGN KEY (country_id) REFERENCES country (country_id) ON DELETE CASCADE;

ALTER TABLE investor ADD CONSTRAINT fk_investor_address FOREIGN KEY (address_id) REFERENCES address (address_id) ON DELETE CASCADE;

ALTER TABLE portfolio ADD CONSTRAINT fk_portfolio_investor FOREIGN KEY (investor_id) REFERENCES investor (investor_id) ON DELETE CASCADE;

ALTER TABLE stock ADD CONSTRAINT fk_stock_segment FOREIGN KEY (segment_id) REFERENCES segment (segment_id) ON DELETE CASCADE;

ALTER TABLE stock_transaction ADD CONSTRAINT fk_transaction_stock FOREIGN KEY (stock_id) REFERENCES stock (stock_id) ON DELETE CASCADE;
ALTER TABLE stock_transaction ADD CONSTRAINT fk_transaction_investor FOREIGN KEY (investor_id) REFERENCES investor (investor_id) ON DELETE CASCADE;

ALTER TABLE verified ADD CONSTRAINT fk_verified_investor FOREIGN KEY (investor_id) REFERENCES investor (investor_id) ON DELETE CASCADE;
-- end

